### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zibri** [defaultnamehere/cookie_crimes#11]
$ python cookie_crimes.py
Traceback (most recent call last):
  File "cookie_crimes.py", line 139, in <module>
    forbidden_process = summon_forbidden_protocol()
  File "cookie_crimes.py", line 100, in summon_forbidden_protocol
    stdout=subprocess.DEVNULL,
AttributeError: 'module' object has no attribute 'DEVNULL'

**Comment by Ret2lib** [comment]
You are are likely using python 2. DEVNULL does not exist for the python 2 version of subprocess.
